### ISSUE TITLE
Questions: RateLimitMiddleware

### ISSUE THREAD

**Issue by codingnetworksb** [brunolnetto/fastapi-auth-mvp#33]
Hi,

I'm very interested in your RateLimitMiddleware. I'm looking to implement a User-based Rate Limitting in FastAPI.  I have tried on my limited knowlegde to do it with "slowapi" and "fastapi-limiter", with no success.

Did you finish and implement your RateLimitMiddleware? Did find a way using "fastapi-limiter" to implement per-user specifics rate limiting?

**Comment by brunolnetto** [comment]
This is still work in progress, although somewhat advance. Keep tuned. I will try to finish this until the end of the day. (Timezone -3 UTC)

**Comment by brunolnetto** [comment]
I was unable to implement fully today.  You can try this though: https://github.com/brunolnetto/fastapi-slowapi-mvp

**Comment by brunolnetto** [comment]
@codingnetworksb You can try [this](https://github.com/laurentS/slowapi/blob/a72bcc66597f620f04bf5be3676e40ed308d3a6a/slowapi/middleware.py#L116) from library `slowapi`. You can try using it as on the example https://slowapi.readthedocs.io/en/latest/examples/.
